version: '3'
services:
    koha:
        image: koha-adp
        tty: true    
        cap_add: 
            - ALL
        ports: 
            - "3308:3306"
            - "8088:8080"
            - "8089:80"
            - "8087:8081"
        volumes: 
            - ./volume/kohadb:/kohadevbox/koha