version: '2.3'
services:
    koha:
        image: adp/koha-dev:1.0.2
        tty: true    
        cap_add: 
            - ALL
        ports:
            - "8081:80"
            - "8082:8080"
#        volumes: 
#            - ./volume/kohadb:/kohadevbox/koha
        depends_on:
            - db

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mBadp2019!
        ports: 
            - "3306:3306"
        volumes:
            - ./volume/mysql:/var/lib/mysql